export { Advantages } from './Advantages';
export { Cleaning } from './Cleaning';
export { Costs } from './Costs';
export { FAQ } from './FAQ';
export { MainOffer } from './MainOffer';
export { Order } from './Order';
export { PriceByPhoto } from './PriceByPhoto';
export { Promotions } from './Promotions';
export { Reviews } from './Reviews';