import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Providers } from '@/components/Providers';
import { Header } from '@/components/Header';

import './globals.css'

interface Props {
  children: React.ReactNode;
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout;
